# This message is compatible with control table of Dynamixel MX Series (MX-64T/MX64-R/MX-64AT/MX-64AR, MX-106T/MX-106R)
# If you want to specific information about control table, please follow the link (http://emanual.robotis.com/)

uint16 model_number
uint8  firmware_version
uint8  model_id
uint8  baud_rate
uint8  return_delay_time
uint16 cw_angle_limit
uint16 ccw_angle_limit
uint8  temperature_limit
uint8  min_voltage_limit
uint8  max_voltage_limit
uint16 max_torque
uint8  status_return_level
uint8  alarm_led
uint8  shutdown
uint16 multi_turn_offset
uint8  resolution_divider

uint8  torque_enable
uint8  led
uint8  d_gain
uint8  i_gain
uint8  p_gain
uint16 goal_position
uint16 moving_speed
uint16 torque_limit
uint16 present_position
uint16 present_speed
uint16 present_load
uint8  present_voltage
uint8  present_temperature
uint8  registered
uint8  moving
uint8  lock
uint16 punch
uint16 current
uint8  torque_control_mode_enable
uint16 goal_torque
uint8  goal_acceleration

