# This message is compatible with control table of Dynamixel XL Series (XL320)
# If you want to specific information about control table, please follow the link (http://emanual.robotis.com/)

uint16 model_number
uint8  firmware_version
uint8  model_id
uint8  baud_rate
uint8  return_delay_time
uint16 cw_angle_limit
uint16 ccw_angle_limit
uint8  control_mode
uint8  temperature_limit
uint8  min_voltage_limit
uint8  max_voltage_limit
uint16 max_torque
uint8  status_return_level
uint8  shutdown

uint8  torque_enable
uint8  led
uint8  d_gain
uint8  i_gain
uint8  p_gain
uint16 goal_position
uint16 moving_speed
uint16 torque_limit
uint16 present_position
uint16 present_speed
uint16 present_load
uint8  present_voltage
uint8  present_temperature
uint8  registered
uint8  moving
uint8  hardware_error_status
uint16 punch
