# Publised by dynamixel_workbench_single_manager_gui and Subscribed by dynamixel_workbench_single_manager
# for changing value of address in a Dynamixel

string command

string addr_name
int64 value

---

bool comm_result
