# Server is dynamixel_workbench_tutorials and Client is dynamixel_workbench_controllers
# This service sends motor position with different unit (radian and raw value)

string unit
float32 pan_pos
float32 tilt_pos
---
float32 pan_pos
float32 tilt_pos
